### ISSUE TITLE
Add CSS solution

### ISSUE THREAD

**Issue by rob-3** [poop-team/project-monorepo#4]

**Comment by Rikimbili** [comment]
We are currently planning on using Tailwind with Headless UI but there is another emerging CSS-in-JS solution called [Stitches](https://stitches.dev/) that plays really well with [Radix-UI](https://www.radix-ui.com/) (Both open-source and made by the same company much like Tailwind and HeadlessUI)

**Comment by rob-3** [comment]
I also like Tailwind + Headless, but if y'all want to try something else I'm in for that.

**Comment by Rikimbili** [comment]
Closing this as the consensus is to use Tailwind CSS
